// enum.ts
export enum TypePriorite {
    SPRINT_MEETING_PLAINING = 'SPRINT_MEETING_PLAINING',
    DALIY_SCRUM = 'DALIY_SCRUM',
    SPRINT_REVIEW = 'SPRINT_REVIEW',
    SPRINT_RETROSPECTIVE = 'SPRINT_RETROSPECTIVE'
  }